#Notes: localhost:8182/iiif/2/1002533.tif - test the json response
# getting an image from the server http://localhost:8182/iiif/2/1002533.tif/full/full/0/default.jpg
# http://localhost:8182/iiif/2/1002535.tif/full/100,100/0/default.jpg [different size image]

version: "3.7"
services:
    cantaloupe:
        image: cantaloupe
        build: .
        ports:
            - 8182:8182
        depends_on:
            - minio

        environment:
            HTTP_HTTP2_ENABLED: "true"
            HTTPS_HTTP2_ENABLED: "true"
            ENDPOINT_IIIF_CONTENT_DISPOSITION: none
            SOURCE_STATIC: S3Source
            S3SOURCE_ENDPOINT: https://yale-image-samples.s3.amazonaws.com
            S3SOURCE_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
            S3SOURCE_SECRET_KEY: $AWS_SECRET_ACCESS_KEY
            S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME: ptiffs
            PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
            PROCESSOR_MANUAL_SELECTIONSTRATEGY_JP2: OpenJpegProcessor
            CACHE_SERVER_DERIVATIVE_ENABLED: "true"
            CACHE_SERVER_DERIVATIVE: S3Cache
            CACHE_SERVIER_DERIVATIVE_TTL_SECONDS: 0
            CACHE_SERVER_PURGE_MISSING: "true"
            CACHE_SERVER_WORKER_ENABLED: "true"
            S3CACHE_ENDPOINT: https://yale-image-samples.s3.amazonaws.com
            S3CACHE_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
            S3CACHE_SECRET_KEY: $AWS_SECRET_ACCESS_KEY
            S3CACHE_BUCKET_NAME: cantaloupe
            S3CACHE_OBJECT_KEY_PREFIX: cache
            LOG_APPLICATION_LEVEL: warn
            LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    minio:
        image: minio/minio
        command: ["server", "/data"]
        ports:
            - 9000:9000
        environment:
            MINIO_ACCESS_KEY: ${MINIO_USERNAME:-minio}
            MINIO_SECRET_KEY: ${MINIO_PASSWORD:-password}
